spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
app:
  activity-log:
    prefix: secret
    host: localhost
    port: 23222
    enabled: false
  file-storage:
    file-domestic-dir: /secret/edc_domestic_income_type.txt
    file-cross-border-dir: /secret/edc_cross_border_income_type.txt